Thales/urls.py
from django.urls import path
from django.urls import include

from inspiration.views import *

urlpatterns = [
    path("", include(("inspiration.urls", "inspiration"), namespace="main_frame")),
]

inspiration/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    path("", hp_controller, name="hp"),
    path("more", learn_more_controller, name="more"),
    path("contact", contact_controller, name="contact"),
    path("podcast", podcast_contact_controller, name="podcast_contact"),
    path("blog/search", search_blog_controller, name="search_blog"),
    path("blog/get/<int:blog_id>", details_blog_controller, name="details_blog"),
    path("message_board/search", get_messages_controller, name="search_message_board")
]

inspiration/models.py
from django.db import models


class Blogs(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=512)
    content = models.TextField()
    user_id = models.IntegerField()
    click_time = models.BigIntegerField()
    image = models.TextField()
    create_time = models.DateTimeField(auto_now=True)
    lastmodified_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "blogs"


class Users(models.Model):
    id = models.BigAutoField(primary_key=True)
    role = models.CharField(max_length=512)
    username = models.CharField(max_length=512)

    class Meta:
        db_table = "users"


class BlogComments(models.Model):
    id = models.BigAutoField(primary_key=True)
    blog_id = models.IntegerField()
    content = models.TextField()
    comment_username = models.CharField(max_length=512)
    create_time = models.DateTimeField(auto_now=True)
    lastmodified_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "blog_comments"


class MessageBoard(models.Model):
    id = models.BigAutoField(primary_key=True)
    random_user = models.CharField(max_length=512)
    title = models.CharField(max_length=512)
    content = models.TextField()
    reply = models.TextField()
    reply_user_id = models.IntegerField()
    create_time = models.DateTimeField(auto_now=True)
    lastmodified_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "message_board"

inspiration/views.py
from django.conf import settings
from django.http import HttpResponse
from django.template import loader

from inspiration.common import constant
from inspiration.utils.common import *
from inspiration.plugins.plugin_redis import RedisClient
from inspiration.logic.blog import *
from inspiration.logic.message_board import *


# Main index show & render
def hp_controller(request):
    r = RedisClient()
    r.incrby(constant.VISIT_CALCULATOR_KEY, 1)

    tpl = loader.get_template('index.html')
    return HttpResponse(tpl.render(build_context(), request))


# Learn more index show & render
def learn_more_controller(request):
    tpl = loader.get_template('learnmore.html')
    r = RedisClient()
    result = r.get(constant.VISIT_CALCULATOR_KEY)
    context = {"calculate_result": result}
    return HttpResponse(tpl.render(merge_context(build_context(), context), request))


# Contact with me
def contact_controller(request):
    tpl = loader.get_template('contact.html')
    return HttpResponse(tpl.render(build_context(), request))


# podcast
def podcast_contact_controller(request):
    tpl = loader.get_template('podcast_contact.html')
    return HttpResponse(tpl.render(build_context(), request))


# Blog query page
def search_blog_controller(request):
    tpl = loader.get_template('blog.html')
    context = {
        "blog_list": get()
    }
    return HttpResponse(tpl.render(merge_context(build_context(), context), request))


def details_blog_controller(request, blog_id):
    tpl = loader.get_template('blog_details.html')
    update_click_time(blog_id)
    context = {
        "blog": get_details(blog_id)
    }
    return HttpResponse(tpl.render(merge_context(build_context(), context), request))


def create_blog_controller(request):
    tpl = loader.get_template('blog.html')
    req = {
        "title": request.POST["title"],
        "content": request.POST["content"]
    }
    create(req)
    return HttpResponse(tpl.render(build_context(), request))


# Message Board
def get_messages_controller(request):
    tpl = loader.get_template('message_board.html')
    context = {
        "messages": get_messages()
    }
    return HttpResponse(tpl.render(merge_context(build_context(), context), request))

inspiration/templates/blog.html
{% extends "index.html" %}
{% load static %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="mb-5">
                <img src="{% static "middle_img.png" %}" alt="Bootstrap" width="550" height="350">
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <div class="d-flex flex-column flex-shrink-0 p-2 text-white bg-dark" style="width: 9rem;">
                    <div class="fs-3 mb-3 text-start">
                        <img src="{% static "svg/bookmark-dash.svg" %}" alt="Bootstrap" width=25" height="25">
                        <a href="/" class="text-white text-decoration-none">
                            <span class="fs-5">Category</span>
                        </a>
                    </div>
                    <hr>
                    <ul class="nav flex-column mb-auto text-start">
                        <li class="nav-item fw-normal">
                            <a href="#" class="nav-link active fw-light text-white" aria-current="page">Home</a>
                        </li>
                        <li>
                            <a href="#" class="nav-link fw-light text-white">DirtyTalks</a>
                        </li>
                        <li>
                            <a href="#" class="nav-link fw-light text-white">Podcasts</a>
                        </li>
                        <li>
                            <a href="#" class="nav-link fw-light text-white">Thinkings</a>
                        </li>
                        <li>
                            <a href="#" class="nav-link fw-light text-white">DayDreaming</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
            </div>
            <div class="col-md-7">
                {% for blog in blog_list %}
                    <div class="card-content" style="width: 25rem;">
                        {% if blog.image %}
                            <img src="{{ blog.image }}" class="card-img-top" alt="image">
                        {% endif %}
                        <div class="card-body">
                            <div class="fs-3 mb-3 text-start">
                                <img src="{% static "svg/book.svg" %}" alt="Bootstrap" width="30" height="30">
                                <span class="fw-normal">{{ blog.title }}</span>
                            </div>
                            <div class="fs-5 mb-3 text-start">
                                <span class="fw-light">{{ blog.content }}</span>
                            </div>
                            <div class="fs-7 mb-3 text-start">
                                <img src="{% static "svg/pen.svg" %}" alt="Bootstrap" width="20" height="20">
                                <span class="fw-light">{{ blog.username }}</span>
                                <img src="{% static "svg/clock.svg" %}" alt="Bootstrap" width="20" height="20">
                                <span class="fw-light">{{ blog.create_time }}</span>
                                <img src="{% static "svg/mouse2.svg" %}" alt="Bootstrap" width="20" height="20">
                                <span class="fw-light">{{ blog.click_time }}</span>
                            </div>
                            <div class="fs-7 mb-3 text-start">
                                <a href="/blog/get/{{ blog.id }}" class="btn btn-outline-success">View Blog</a>
                            </div>
                        </div>
                        <br>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock main %}

inspiration/templates/blog_details.html
{% extends "index.html" %}
{% load static %}

{% block main %}
    <main class="px-3">
        <div class="card-content" style="width: 30rem;">
            {% if blog.image %}
                <img src="{{ blog.image }}" class="card-img-top" alt="image">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title">{{ blog.title }}</h4><br>
                <p class="card-text">{{ blog.content }}</p>
                <h6 class="card-subtitle mb-2 text-muted">{{ blog.username }} / {{ blog.click_time }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Create {{ blog.create_time }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Update {{ blog.lastmodified_time }}</h6>
                <a href="/blog/search" class="btn btn-outline-success">Back</a>
            </div>
            <br>
            <div>Comments</div>
            <br>
            {% if blog.comments|length == 0 %}
                <h6 class="card-title">暂无评论</h6><br>
            {% endif %}
            {% for comment in blog.comments %}
                <h6 class="card-title">{{ comment.comment_username }}</h6><br>
                <h6 class="card-title">{{ comment.content }}</h6><br>
                <h6 class="card-title">{{ comment.create_time }}</h6><br>
            {% endfor %}
        </div>
    </main>
{% endblock main %}

inspiration/templates/contact.html
{% extends "index.html" %}
{% load static %}

{% block main %}
<main class="px-3">
    <img src="{% static "wc_qrcode.png" %}" alt="qrcode" height=300 width="300">
</main>
{% endblock main %}

inspiration/templates/index.html
{% load static %}

<!doctype html>

<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>芙洛特魔方世界</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">
    <link href="{% static "plugins/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "plugins/bootstrap/css/cover.css" %}" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    {% block headers %}
    <header class="mb-auto">
        <div>
            <h2 class="float-md-start mb-0">Floater</h2>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                {% for navbar in navbars %}
                    <a class="nav-link fw-bold py-1 px-0" aria-current="page"
                       href="{{ navbar.link }}">{{ navbar.show }}</a>
                {% endfor %}
            </nav>
        </div>
    </header>
    {% endblock headers %}

    {% block main %}
    <main class="px-3">
        <h1>Floater's World</h1>
        <p class="lead">Inspirations and Explorations.</p>
        <p class="lead">
            <a href="{% url "main_frame:more" %}" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn
                more</a>
        </p>
    </main>
    {% endblock main %}

    {% block footer %}
    <footer class="mt-auto text-white-50">
        <p>To contact with me, Click here: <a href="{% url "main_frame:contact" %}"
                                                        class="text-white">Floater</a></p>
    </footer>
    {% endblock footer %}
</div>

</body>
</html>

inspiration/templates/learnmore.html
{% extends "index.html" %}
{% load static %}

{% block main %}
<main class="px-3">
    <h4>Calculator: <br><br>Our website was visited by<br><br></h4>
    <h1>{{ calculate_result }}</h1> <br><br>
    <h4>times! </h4>
</main>
{% endblock main %}

inspiration/templates/message_board.html
{% extends "index.html" %}
{% load static %}

{% block main %}
    <div class="mb-3">
        {% for message in messages %}
            <div class="row text-start mb-5">
                <div class="col-md-4 mb-3">
                    <div class="mb-2">
                        <img src="{% static "svg/person.svg" %}" alt="image" width=25" height="25">
                        <span class="fw-light">{{ message.random_user }}</span>
                    </div>
                    <div class="mb-2">
                        <img src="{% static "svg/clock.svg" %}" alt="image" width=25" height="25">
                        <span class="fw-light">{{ message.create_time }}</span>
                    </div>
                </div>
                <div class="col-md-8 mb-3">
                    <div class="fs-4 mb-1">
                        <span class="fw-bolder">{{ message.title }}</span>
                    </div>
                    <div class="fs-6 mb-1">
                        <span class="fw-light">{{ message.content }}</span>
                    </div>
                    <div class="fs-6 text-success mb-1">
                        {% if message.reply %}
                            <span class="fw-normal">【{{ message.reply_user_role }}】 {{ message.reply_username }} Replied: {{ message.reply }}</span>
                        {% endif %}
                    </div>
                </div>
                <hr>
            </div>
        {% endfor %}
        <div class="fs-3 mb-4">
            <img src="{% static "svg/airplane-engines.svg" %}" alt="image" width=50" height="50">
            <span class="fw-light">Write down your messages!</span>
        </div>
        <div class="row mb-4">
            <label for="nickname" class="col-sm-2 col-form-label text-start">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nickname" placeholder="Please fill your nickname..."
                       required>
            </div>
        </div>
        <div class="row mb-4">
            <label for="messageTitle" class="col-sm-2 col-form-label text-start">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="messageTitle" placeholder="Please fill your title..."
                       required>
            </div>
        </div>
        <div class="row mb-2">
            <label for="messageTextArea" class="col-sm-2 col-form-label text-start">Messages</label>
            <div class="col-sm-10">
                <textarea class="form-control" id="messageTextArea" rows=7 placeholder="Please fill messages..."
                          required></textarea>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-auto m-1">
            <button type="submit" class="btn btn-primary">Submit Message</button>
        </div>
        <div class="col-md-auto m-1">
            <button type="submit" class="btn btn-primary">Clean Message</button>
        </div>
        <div class="col-md-3"></div>
    </div>
{% endblock main %}

inspiration/templates/podcast_contact.html
{% extends "index.html" %}
{% load static %}

{% block main %}
<main class="px-3">
    <img src="{% static "podcast_qrcode.png" %}" alt="qrcode" height=350 width="300">
</main>
{% endblock main %}